### ISSUE TITLE
Bar view: brewery detail/order page

### ISSUE THREAD

**Issue by kurt-leingang** [beer-gang/beer-gang#23]
Tasks:

- [ ] ~update URL to "/pour/breweries/:id"~

- [x] rename Size nomenclature from "sixtel" and "full" to "1/6 bbl" and "1/2 bbl"

- [x] replace "Description" with new "Subtitle" field. Description will only be viewable from the beer info page /pour/beers/:id

**Comment by kurt-leingang** [comment]
For Size nomenclature: I think it might look better to rename "Size" to "Size (bbl)" that way the list shows "1/2" and "1/6" instead of "1/2 bbl" and "1/6 bbl". Just a bit cleaner.

**Comment by zabrador** [comment]
Fixed all changes but the route, I wanna wait to spend time on that until we're sure how the split is gonna wind up happening. As I've been building these pages, it's seeming more and more like we may want to just leave them consolidated. For example, breweries will probably want to see what their display page will look like from a bar's perspective, right?

**Comment by kurt-leingang** [comment]
Yes they will, but they'll also want to be able to view the difference. Can
we have both?

**Comment by kurt-leingang** [comment]
You're correct; they definitely will.
